[project]
name = "my-mcp-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.52.2",
    "mcp[cli]>=1.9.2",
    "openai>=1.84.0",
    "pydantic-ai>=0.2.14",
]
